"""Behavioral contract for code-reviewed provider adapters."""
from typing import Protocol

class ProviderAdapter(Protocol):
    def preflight(self, *, backup: bool = False) -> dict: ...
    def prepare_deploy(self) -> dict: ...
    def finish_deploy(self) -> dict: ...
    def health(self, *, require_healthy: bool = False) -> dict: ...
    def check(self) -> dict: ...
    def backup(self, mode: str = "backup") -> dict: ...
    def recovery_info(self) -> dict: ...
    def verify_recovery(self) -> dict: ...
