"use strict";
const $ = id => document.getElementById(id);
const state = {config:null, authenticated:false, selected:null, tasks:[], pending:false, polling:false, outputCache:new Map(), summary:null};
function text(id,value){$(id).textContent=String(value);}
function showError(message){text("error",message);$("error").hidden=false;}
function clearError(){$("error").hidden=true;}
function safeLink(id,value){try{const u=new URL(value);if(u.protocol!=="https:"||u.username||u.password)return;$(id).href=u.href;$(id).hidden=false;}catch(_){}}
async function api(path, options={}){
 const response=await fetch("/api"+path,{credentials:"same-origin",cache:"no-store",headers:{"Content-Type":"application/json"},...options,signal:AbortSignal.timeout(15000)});
 if(response.status===401||response.status===403){state.authenticated=false;showLogin();throw new Error("Sign in with the management owner account, then return to this page.");}
 if(!response.ok)throw new Error(`The console returned HTTP ${response.status}. Inspect activity before retrying a submitted operation.`);
 const body=await response.text();return body?JSON.parse(body):null;
}
function showLogin(){const n=$("session");n.replaceChildren(document.createTextNode("Sign in through Semaphore, complete two-factor authentication, then return here. "));const a=document.createElement("a");a.href="/";a.textContent="Open secure sign-in →";n.append(a);text("connection-state","Signed out");setButtons();}
function setButtons(){document.querySelectorAll("#actions button").forEach(b=>b.disabled=!state.authenticated||state.pending);$("refresh").disabled=!state.authenticated||state.pending;}
function timestamp(value){if(!value)return "Not recorded";const d=new Date(value);return Number.isNaN(d.valueOf())?"Unknown time":d.toLocaleString(undefined,{dateStyle:"medium",timeStyle:"short"});}
function taskName(t){return Object.values(state.config.operations).find(op=>Number(op.id)===Number(t.template_id))?.title||`Operation #${t.id}`;}
function resultFromOutput(rows){const lines=rows.map(x=>x.output||"").join("\n");const matches=[...lines.matchAll(/CLOUDOPS_RESULT_B64=([A-Za-z0-9+/=]+)/g)];for(let i=matches.length-1;i>=0;i--){try{const bytes=Uint8Array.from(atob(matches[i][1]),c=>c.charCodeAt(0));return JSON.parse(new TextDecoder().decode(bytes));}catch(_){}}return null;}
function renderSummary(r){if(!r)return;state.summary=r;
 if(r.checked_at){const age=Date.now()-new Date(r.checked_at).getTime();const stale=!Number.isFinite(age)||age>15*60*1000;text("checked-at",`Last application check: ${timestamp(r.checked_at)}${stale?" · Historical result. Run a new check before relying on it.":" · This is a point-in-time check, not continuous monitoring."}`);$("checked-at").classList.toggle("warning-text",stale);text("health",r.application_verified?"Checks passed":"Needs attention");$("health").classList.toggle("good",r.application_verified===true);text("health-note",r.application_verified?`Nextcloud ${r.version||""} passed internal checks; external reachability is not tested here.`:"Complete onboarding or inspect the latest operation.");}
 if(Number.isFinite(r.data_free_bytes)){text("storage",`${(r.data_free_bytes/(1024**3)).toLocaleString(undefined,{maximumFractionDigits:1})} GiB`);text("storage-note",r.data_mount_verified?"Required data mount identity verified.":"Mount verification is not available.");}
 const b=r.last_backup;if(b?.backup_verified){text("backup","Verified");$("backup").classList.add("good");text("backup-note",`${timestamp(b.finished_at)} · Fresh archive and successful Borg exit.`);}else if(Object.hasOwn(r,"last_backup")){text("backup","Not recorded");$("backup").classList.remove("good");text("backup-note","Run a verified backup after native AIO setup.");}
 const recovery=r.last_restore_test;if(recovery?.restore_verified){text("recovery","Probe passed");$("recovery").classList.add("good");text("recovery-note",`${timestamp(recovery.verified_at)} · One file/account only; not the entire cloud.`);}else if(Object.hasOwn(r,"last_restore_test")){text("recovery","Not tested");$("recovery").classList.remove("good");text("recovery-note","Use a distinct recovery-test host and the original probe.");}
}
async function output(t,refresh=false){const cached=state.outputCache.get(t.id);if(cached&&!refresh&&!['running','waiting','starting','stopping'].includes(t.status))return cached;const rows=await api(`/project/${state.config.project_id}/tasks/${t.id}/output`);state.outputCache.set(t.id,rows||[]);return rows||[];}
function renderHistory(){const h=$("history");h.replaceChildren();if(!state.tasks.length){const p=document.createElement("p");p.className="muted";p.textContent="No operations yet. Start with Install cloud, then complete AIO setup.";h.append(p);return;}for(const t of state.tasks.slice(0,30)){const b=document.createElement("button");b.className="history-item"+(Number(t.id)===Number(state.selected)?" selected":"");const title=document.createElement("strong");title.textContent=taskName(t);const desc=document.createElement("small");desc.textContent=`#${t.id} · ${t.status||"unknown"} · ${timestamp(t.created)}`;b.append(title,desc);b.addEventListener("click",()=>selectTask(t.id));h.append(b);}}
async function selectTask(id){state.selected=Number(id);try{localStorage.setItem("cloudops-selected",String(id));}catch(_){}renderHistory();const t=state.tasks.find(item=>Number(item.id)===state.selected);if(!t)return;const rows=await output(t,true);if(Number(id)!==state.selected)return;text("log-title",taskName(t));text("log-status",t.status||"unknown");const result=resultFromOutput(rows);text("job-note",result?.job_id?`Host job ${result.job_id} · ${result.status||"see output"}`:"A console task can disconnect while the host continues working. Check host history before retrying.");text("log-output",rows.map(item=>item.output||"").join("\n").replace(/CLOUDOPS_RESULT_B64=[A-Za-z0-9+/=]+/g,"[structured status recorded]")||"Waiting for execution output…");}
async function refreshHistory(){if(state.polling||!state.authenticated)return;state.polling=true;try{state.tasks=(await api(`/project/${state.config.project_id}/tasks/last`)||[]).sort((a,b)=>Number(b.id)-Number(a.id));renderHistory();const checks=state.tasks.filter(t=>Number(t.template_id)===Number(state.config.operations.check.id)&&t.status==='success');if(checks.length){const r=resultFromOutput(await output(checks[0]));if(r?.status==='success')renderSummary(r);}
 if(state.selected===null&&state.tasks.length)state.selected=state.tasks[0].id;
 if(state.selected!==null)await selectTask(state.selected);text("connection-state","Connected · refreshes every 5 seconds");
 }catch(e){showError(e.message);text("connection-state","Connection needs attention");}finally{state.polling=false;}}
async function submit(op){if(state.pending)return;state.pending=true;setButtons();clearError();try{const spec=state.config.operations[op];const body={template_id:spec.id,environment:JSON.stringify(spec.confirmation?{cloudops_confirmation:"PROCEED"}:{})};const task=await api(`/project/${state.config.project_id}/tasks`,{method:"POST",body:JSON.stringify(body)});if(!task?.id)throw new Error("Submission response did not include a task ID. Inspect history before retrying.");state.selected=task.id;try{localStorage.setItem("cloudops-selected",String(task.id));}catch(_){}await refreshHistory();$("activity").scrollIntoView({behavior:"smooth",block:"start"});}catch(e){showError(`${e.message} A submission may already have reached the server; do not repeatedly tap the action.`);}finally{state.pending=false;setButtons();}}
function requestOperation(op){const spec=state.config.operations[op];if(!spec.confirmation){submit(op);return;}text("confirm-title",spec.title);text("confirm-description",spec.description);$("approval").checked=false;$("confirm-submit").disabled=true;const dialog=$("confirm-dialog");dialog.returnValue="cancel";dialog.onclose=()=>{if(dialog.returnValue==='approve'&&$("approval").checked)submit(op);};dialog.showModal();}
function actions(){const container=$("actions");container.replaceChildren();const order=["check","backup","backup_check","verify","deploy","recovery_info","verify_recovery"];for(const op of order){const spec=state.config.operations[op];if(!spec||(op==='verify_recovery'&&state.config.mode!=="recovery-test"))continue;const b=document.createElement("button");b.className="action";b.dataset.operation=op;b.disabled=true;for(const [cls,value] of [["action-title",spec.title],["action-desc",spec.description],["action-type",spec.confirmation?"Review & approve →":"Run check →"]]){const span=document.createElement("span");span.className=cls;span.textContent=value;b.append(span);}b.addEventListener("click",()=>requestOperation(op));container.append(b);}}
async function boot(){try{const response=await fetch("config.json",{cache:"no-store"});if(!response.ok)throw new Error("Setup has not provisioned the portal configuration.");state.config=await response.json();if(!Number.isInteger(state.config.project_id)||!state.config.operations?.check)throw new Error("Finish management setup before using browser operations.");text("instance-name",state.config.instance_id);text("provider-label",`${state.config.provider} · ${state.config.mode}`);$("demo-banner").hidden=state.config.demo!==true;safeLink("open-cloud",state.config.cloud_url);safeLink("open-aio",state.config.aio_url);actions();try{state.selected=Number(localStorage.getItem("cloudops-selected"))||null;}catch(_){}
 const user=await api("/user/");state.authenticated=true;text("session",`Signed in as ${user.name||user.username||"owner"}. Management stays separate from your file-sharing application.`);setButtons();await refreshHistory();setInterval(refreshHistory,5000);
 }catch(e){showError(e.message);}}
$("approval").addEventListener("change",()=>{$("confirm-submit").disabled=!$("approval").checked;});$("refresh").addEventListener("click",()=>requestOperation("check"));document.addEventListener("visibilitychange",()=>{if(!document.hidden)refreshHistory();});boot();
